export const siteConfig = {
  name: "Printora",
  tagline: "Turn Any Windows Printer Into a Printer You Can Use From Anywhere.",
  headline: "Turn Any Windows Printer Into a Printer You Can Use From Anywhere.",
  subheadline: "Print from your phone to any printer connected to your Windows PC — over Wi-Fi, 4G, 5G, or any internet connection.",
  supportingLine: "Your Windows PC becomes a secure print bridge, powered by Cloudflare Tunnel.",
  description: "Turn Any Windows Printer Into a Printer You Can Use From Anywhere. Print from your phone to any printer connected to your Windows PC — over Wi-Fi, 4G, 5G, or any internet connection. Powered by Cloudflare Tunnel.",
  url: "https://printora.app",
  githubUrl: "https://github.com/sagarsahni6/wifi-print",
  windowsDownloadUrl: "/download/windows",
  androidDownloadUrl: "/download/android",
  navItems: [
    { label: "Features", href: "/#features" },
    { label: "How It Works", href: "/how-it-works" },
    { label: "Scanner", href: "/#scanner" },
    { label: "Security", href: "/security" },
    { label: "Compatibility", href: "/compatibility" },
    { label: "FAQ", href: "/faq" },
  ],
  solutions: [
    { title: "Print from Android", href: "/print-from-android-to-windows-printer" },
    { title: "Print from iPhone", href: "/print-from-iphone-to-windows-printer" },
    { title: "Print from iPad", href: "/print-from-ipad-to-windows-printer" },
    { title: "Print to USB Printer", href: "/print-from-phone-to-usb-printer" },
    { title: "Remote 4G/5G Print", href: "/remote-printing-from-phone" },
    { title: "ID Card to A4 PDF", href: "/id-card-scanner-to-pdf" },
    { title: "Phone Scan to PDF", href: "/mobile-document-scanner-to-pdf" },
    { title: "QR Web Print Architecture", href: "/qr-code-web-printing" },
  ],
  featureSubnav: [
    { title: "Wireless Printing", href: "/features/wireless-printing", desc: "Print directly from Android or browser" },
    { title: "Document Scanner", href: "/features/document-scanner", desc: "Camera scanner with edge detection & OCR" },
    { title: "ID Card Scanner", href: "/features/id-card-scanner", desc: "Front & back combined to single A4" },
    { title: "OCR Text Extraction", href: "/features/ocr", desc: "Extract text directly from scanned pages" },
    { title: "Remote Printing", href: "/features/remote-printing", desc: "Print over 4G/5G via Cloudflare Tunnel" },
    { title: "QR Web Print", href: "/features/web-print", desc: "Zero-install printing for iPhone & browser" },
    { title: "Printer Management", href: "/features/printer-management", desc: "Queue controls, health, and supplies" },
  ],
  productFacts: {
    productName: "Printora",
    category: "Wireless Printing & Mobile Document Scanning Utility",
    hostOS: "Windows 10 / Windows 11 (64-bit, .NET 8)",
    androidApp: "Native Kotlin & Jetpack Compose (Android 8.0+)",
    iosSupport: "Browser-based QR Web Print (Safari on iOS 14+)",
    browserSupport: "Any modern web browser (Chrome, Safari, Edge, Firefox)",
    localDiscovery: "mDNS (Multicast DNS) + UDP Beacon Broadcast fallback",
    networkArchitecture: "Local-first direct Wi-Fi / LAN communication",
    remoteOption: "Optional secure Cloudflare Tunnel with PIN/token auth",
    encryption: "TLS communication with SHA-256 certificate fingerprint pinning",
    privacyModel: "Zero permanent cloud document storage; automatic temp-file cleanup",
    scannerCapacity: "Up to 20 pages per document session",
    supportedFormats: ["PDF", "JPG", "JPEG", "PNG", "BMP", "GIF", "TXT", "DOC", "DOCX*"],
    docRequirement: "*DOC/DOCX conversion requires LibreOffice installed on host PC",
    defaultWebLimits: "Max 3 copies, max 30 PDF pages, 2 jobs/min rate limit per IP",
  }
};
